// ═══════════════════════════════════════════════
// DIGITALIUM.IO — Formation Config: SysAdmin
// ═══════════════════════════════════════════════

import type { FormationConfig } from "@/types/formation";

export const SYSADMIN_FORMATION: FormationConfig = {
    espaceRole: "sysadmin",
    titreBienvenue: "Bienvenue, Administrateur Système",
    descriptionRole: "En tant qu'administrateur système, vous êtes responsable de l'infrastructure technique, de la sécurité et de la performance de la plateforme DIGITALIUM.IO. Cet espace vous offre tous les outils nécessaires pour surveiller, configurer et optimiser la plateforme.",
    responsabilites: [
        "Surveiller l'infrastructure et les performances système",
        "Gérer la sécurité : firewall, SSL, contrôle d'accès",
        "Administrer les bases de données et les sauvegardes",
        "Configurer les rôles et permissions (IAM)",
        "Gérer les organisations clientes et abonnements",
        "Maintenir les templates de workflows",
        "Analyser les logs et résoudre les incidents",
        "Personnaliser le thème et la configuration de la plateforme",
    ],
    fonctionnalites: [
        {
            id: "infra",
            onglet: "Infrastructure",
            icone: "MonitorDot",
            titre: "Gestion de l'Infrastructure",
            description: "Surveillez vos serveurs, gérez la maintenance et provisionnez de nouvelles ressources.",
            importance: "Critique",
            tutorielIds: ["tut-infra-1", "tut-infra-2"],
        },
        {
            id: "monitoring",
            onglet: "Monitoring",
            icone: "BarChart3",
            titre: "Monitoring en Temps Réel",
            description: "Suivez les métriques CPU, RAM, réseau et configurez les alertes automatiques.",
            importance: "Critique",
            tutorielIds: ["tut-monitor-1"],
        },
        {
            id: "security",
            onglet: "Sécurité",
            icone: "Shield",
            titre: "Sécurité & Conformité",
            description: "Gérez les règles firewall, certificats SSL et l'audit de sécurité.",
            importance: "Critique",
            tutorielIds: ["tut-secu-1"],
        },
        {
            id: "iam",
            onglet: "IAM",
            icone: "Lock",
            titre: "Identités & Accès (IAM)",
            description: "Configurez les rôles, permissions et politiques d'accès à la plateforme.",
            importance: "Haute",
            tutorielIds: ["tut-iam-1"],
        },
        {
            id: "db",
            onglet: "Databases",
            icone: "Database",
            titre: "Bases de Données",
            description: "Administrez les instances, réplicas et sauvegardes de vos bases de données.",
            importance: "Haute",
            tutorielIds: ["tut-db-1"],
        },
        {
            id: "clients",
            onglet: "Gestion",
            icone: "Users",
            titre: "Gestion des Clients",
            description: "Gérez les organisations clientes, abonnements et leads commerciaux.",
            importance: "Moyenne",
            tutorielIds: ["tut-clients-1"],
        },
    ],
    tutoriels: [
        {
            id: "tut-infra-1",
            titre: "Vérifier l'état de l'infrastructure",
            fonctionnaliteId: "infra",
            etapes: [
                { numero: 1, instruction: "Accédez à la section Infrastructure", detail: "Menu latéral → Infrastructure" },
                { numero: 2, instruction: "Consultez le tableau des serveurs", detail: "Vérifiez que tous les statuts sont «En ligne»" },
                { numero: 3, instruction: "Vérifiez l'utilisation des ressources", detail: "CPU < 80%, RAM < 85% est recommandé" },
                { numero: 4, instruction: "Identifiez les alertes éventuelles", detail: "Les lignes rouges signalent des problèmes" },
            ],
            routeCible: "/sysadmin/infrastructure",
        },
        {
            id: "tut-infra-2",
            titre: "Activer le mode maintenance",
            fonctionnaliteId: "infra",
            etapes: [
                { numero: 1, instruction: "Sélectionnez le serveur à mettre en maintenance" },
                { numero: 2, instruction: "Cliquez sur le bouton «Maintenance»", detail: "Un message de confirmation apparaîtra" },
                { numero: 3, instruction: "Confirmez l'action", detail: "Le serveur sera signalé comme «En maintenance»" },
                { numero: 4, instruction: "Planifiez la durée de maintenance", detail: "Informez les utilisateurs si nécessaire" },
            ],
            routeCible: "/sysadmin/infrastructure",
        },
        {
            id: "tut-monitor-1",
            titre: "Configurer une alerte de performance",
            fonctionnaliteId: "monitoring",
            etapes: [
                { numero: 1, instruction: "Accédez à la section Monitoring" },
                { numero: 2, instruction: "Cliquez sur «Configurer les seuils»" },
                { numero: 3, instruction: "Définissez le seuil CPU", detail: "Recommandé : alerte à 80%" },
                { numero: 4, instruction: "Définissez le seuil RAM", detail: "Recommandé : alerte à 85%" },
                { numero: 5, instruction: "Activez les notifications par email" },
                { numero: 6, instruction: "Enregistrez la configuration" },
            ],
            routeCible: "/sysadmin/monitoring",
        },
        {
            id: "tut-secu-1",
            titre: "Vérifier les certificats SSL",
            fonctionnaliteId: "security",
            etapes: [
                { numero: 1, instruction: "Accédez à la section Sécurité" },
                { numero: 2, instruction: "Consultez le tableau «Certificats SSL»" },
                { numero: 3, instruction: "Vérifiez les dates d'expiration", detail: "Les certificats expirant sous 30 jours sont signalés en orange" },
                { numero: 4, instruction: "Renouvelez les certificats si nécessaire", detail: "Cliquez «Renouveler» pour lancer le processus" },
            ],
            routeCible: "/sysadmin/security",
        },
        {
            id: "tut-iam-1",
            titre: "Créer un nouveau rôle",
            fonctionnaliteId: "iam",
            etapes: [
                { numero: 1, instruction: "Accédez à IAM (Identités & Accès)" },
                { numero: 2, instruction: "Cliquez sur «Créer un rôle»" },
                { numero: 3, instruction: "Nommez le rôle et définissez le niveau", detail: "Le niveau détermine la hiérarchie (0 = system_admin)" },
                { numero: 4, instruction: "Sélectionnez les permissions", detail: "Cochez les permissions nécessaires dans la matrice" },
                { numero: 5, instruction: "Enregistrez le rôle" },
            ],
            routeCible: "/sysadmin/iam",
        },
        {
            id: "tut-db-1",
            titre: "Lancer une sauvegarde manuelle",
            fonctionnaliteId: "db",
            etapes: [
                { numero: 1, instruction: "Accédez à Bases de Données" },
                { numero: 2, instruction: "Sélectionnez l'instance à sauvegarder" },
                { numero: 3, instruction: "Cliquez sur «Sauvegarde manuelle»", detail: "La sauvegarde peut prendre plusieurs minutes" },
                { numero: 4, instruction: "Vérifiez le statut dans l'historique des sauvegardes" },
            ],
            routeCible: "/sysadmin/databases",
        },
        {
            id: "tut-clients-1",
            titre: "Ajouter une nouvelle organisation",
            fonctionnaliteId: "clients",
            etapes: [
                { numero: 1, instruction: "Accédez à Clients" },
                { numero: 2, instruction: "Cliquez sur «Créer un client»" },
                { numero: 3, instruction: "Renseignez les informations de l'organisation", detail: "Nom, adresse, contact principal" },
                { numero: 4, instruction: "Sélectionnez le plan d'abonnement" },
                { numero: 5, instruction: "Validez la création" },
            ],
            routeCible: "/sysadmin/clients",
        },
    ],
    faq: [
        { question: "Comment redémarrer un serveur qui ne répond plus ?", reponse: "Accédez à Infrastructure, sélectionnez le serveur concerné et utilisez le bouton «Redémarrer». Si le serveur ne répond pas du tout, contactez l'hébergeur directement.", categorie: "Infrastructure" },
        { question: "Que faire si le CPU est constamment au-dessus de 90% ?", reponse: "Vérifiez d'abord les processus actifs dans Monitoring. Si c'est un pic temporaire, attendez. Si c'est persistant, envisagez de scaler horizontalement (ajouter des instances) ou verticalement (augmenter les ressources).", categorie: "Monitoring" },
        { question: "Comment réinitialiser le mot de passe d'un utilisateur ?", reponse: "Accédez à Utilisateurs, trouvez l'utilisateur concerné, cliquez sur «Actions» puis «Réinitialiser le mot de passe». Un email sera envoyé à l'utilisateur.", categorie: "Gestion" },
        { question: "Comment restreindre l'accès à un module spécifique ?", reponse: "Utilisez IAM pour modifier les permissions du rôle concerné. Décochez la permission liée au module que vous souhaitez restreindre.", categorie: "Sécurité" },
        { question: "À quelle fréquence les sauvegardes automatiques sont-elles effectuées ?", reponse: "Les sauvegardes automatiques sont effectuées toutes les 6 heures par défaut. Vous pouvez modifier cette fréquence dans Bases de Données → Configuration.", categorie: "Bases de Données" },
        { question: "Comment ajouter un nouveau plan d'abonnement ?", reponse: "Accédez à Abonnements, cliquez sur «Créer un plan», définissez les caractéristiques (nom, prix, fonctionnalités incluses) et publiez-le.", categorie: "Gestion" },
    ],
};
